# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_component_serial_manager_usb_cdc_LPC55S28 true)
set(CONFIG_USE_middleware_usb_device_ip3511fs_LPC55S28 true)
set(CONFIG_USE_component_serial_manager_uart_LPC55S28 true)
set(CONFIG_USE_driver_flexcomm_usart_LPC55S28 true)
set(CONFIG_USE_middleware_baremetal_LPC55S28 true)
